name: food
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_animate:
  camera: ^0.10.5+5
  camera_android_camerax: ^0.5.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  path_provider:

  dio: ^5.3.3
  flutter: 
    sdk: flutter
  # cached_network_image: ^3.3.0
  function_tree: ^0.9.0
  photo_view: ^0.14.0

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
 

